### PR TITLE
Favourite movie

### PR DESCRIPTION
**Pull request by pardhudatla**

### CODE REVIEW

**Review by KRjitendrasaw — CHANGES_REQUESTED** [review]
In line 7 , there is not necessity of this line. you simply return the else.

**Comment by pardhudatla** [comment]
@KRjitendrasaw 

I just Made my changes please check this assignment once

**Review by KRjitendrasaw — APPROVED** [review]

**Comment by KRjitendrasaw** [comment]
i approved your changes.

**Comment by pardhudatla** [comment]
@KRjitendrasaw 

After Your Approval 
I have merged my assignment



Thank You

**Comment by KRjitendrasaw** [comment]
welcome bro

**Pull request merged**
